### ISSUE TITLE
change node to Telerik back-end services

### ISSUE THREAD

**Issue by nelfurion** [Team-Manhattan/Soldier-Heroes#5]
Node doesn't support by default some of the features in the application and Telerik back-end services seems like the better option.

**Comment by M-Yankov** [comment]
info from [TelerikAcademy forum](http://telerikacademy.com/Forum/Questions/179370/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC-%D1%81-%D0%B8%D0%BD%D1%81%D1%82%D0%B0%D0%BB%D0%B0%D1%86%D0%B8%D0%B8-%D1%87%D1%80%D0%B5%D0%B7-bower-package-manager-%D0%BF%D1%80%D0%B5%D0%B7-%D0%BC%D1%80%D0%B5%D0%B6%D0%B0%D1%82%D0%B0-%D0%BD%D0%B0-%D0%A2%D0%B5%D0%BB%D0%B5%D1%80%D0%B8%D0%BA-%D0%90%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%8F#forum-post-179404) about installing it with **npm**
